version: 2.1
orbs:
  slack: circleci/slack@4.1

jobs:

  build:
    docker:
      - image: mrseccubus/github-pages:latest
    steps:
      - run: (cd /root/;rm -rf project;mkdir project)
      - checkout
      - run:
          name: Build and check
          command: |
            echo "*** Building and checking ***"; 
            gem install -N jekyll-secinfo jekyll-last-modified-at
            ./update.sh
            # Removing some stubs
            rm -f _cves/CVE-3000-* csirt.divd.nl/_cves/CVE-3000-*
            rm -rf _cases/DIVD-3000-0000* csirt.divd.nl/_cases/DIVD-3000-0000*
            jekyll build 2>&1| tee jekyll-build.log;
            ./proof_html.sh 
      - save_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - "/root/project/_site"
      - slack/notify:
          channel: ABCXYZ
          event: fail
          template: basic_fail_1

  upload:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Install software
          command: |
            apk update;
            apk add rsync openssh;
            echo "set ftp:passive-mode true" > ~/.lftprc
      - restore_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys:
          fingerprints:
            4a:b2:60:17:4d:ff:27:80:68:5a:66:89:6f:bd:73:59
      - run:
          name: Upload
          command: |
            mkdir -p ~/.ssh;
            echo  "upload.bit.nl,213.136.12.217 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIVx+0N0LECcGHPywPCk9uz4/l3kNUVNe5QQRleIkMCTarkYauvRrPNPl49x3LIjF6cZsmQZX7jwgsJqEzfcF98=" > ~/.ssh/known_hosts;
            cd /root/project/_site;
            rsync -av "--exclude=data/*" --delete . www-divd@upload.bit.nl:htdocs/divd-nl;
            rsync -av .htaccess www-divd@upload.bit.nl:htdocs/divd-nl;

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build:
        context: Slack
      - upload:
          requires:
            - build
          filters:
            branches:
              only:
                - main