publish_mode: editorial_workflow
site_url: https://www.divd.nl
backend:
  name: github
  repo: DIVD-NL/web-www
  branch: main

media_folder: /images
public_folder: /uploads

collections: # A list of collections the CMS should be able to edit
